# Generated by Django 4.2.30 on 2026-07-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('args', models.JSONField(default=list)),
                ('kwargs', models.JSONField(default=dict)),
                ('exception', models.TextField()),
                ('traceback', models.TextField(blank=True, default='')),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-failed_at'],
            },
        ),
    ]
